name: Pull Requests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - "renovate/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pull-request:
    name: PR
    uses: canonical/observability/.github/workflows/charm-pull-request.yaml@2d9c2785529ae65a4c6f1a75161106485d712f08 # v1
    secrets: inherit
    with:
      provider: lxd
