name: Pull Requests

on:
  pull_request:
    branches:
      - main
      - track/**
  push:
    branches:
      - "renovate/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pull-request:
    name: PR
    uses: canonical/observability/.github/workflows/charm-pull-request.yaml@f09a6a6b1982e7c8d8fb84b1cfd73070b44a1ca2 # v1
    secrets: inherit
    with:
      provider: machine
