name: Pull Requests

on:
  pull_request:
    branches:
      - main
      - track/**
  push:
    branches:
      - "renovate/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pull-request:
    name: PR
    uses: canonical/observability/.github/workflows/charm-pull-request.yaml@c13b2b9fedaf3e22861bd15ae4e53ad6506b5523 # v1
    secrets: inherit
    with:
      provider: machine
