name: Quality Gates

on:
  # Manual trigger
  workflow_dispatch:
  # Run the quality checks periodically
  # FIXME: adjust the frequency as needed once we have actual gates in place
  # schedule:
  #   - cron: "0 0 * * Tue"


jobs:
  quality-gates:
    name: Run quality gates
    uses: canonical/observability/.github/workflows/charm-quality-gates.yaml@c13b2b9fedaf3e22861bd15ae4e53ad6506b5523 # v1
    secrets: inherit
