name: Quality Gates

on:
  # Manual trigger
  workflow_dispatch:
  # Run the quality checks periodically
  # FIXME: adjust the frequency as needed once we have actual gates in place
  # schedule:
  #   - cron: "0 0 * * Tue"


jobs:
  quality-gates:
    name: Run quality gates
    uses: canonical/observability/.github/workflows/charm-quality-gates.yaml@f09a6a6b1982e7c8d8fb84b1cfd73070b44a1ca2 # v1
    secrets: inherit
