name: Release Charm

on:
  push:
    branches:
      - main
      - track/**
    paths-ignore:
      - ".github/renovate*"
      - ".github/workflows/release.yaml"
      - ".github/workflows/renovate.yaml"
      - ".github/workflows/update-libs.yaml"
      - ".gitignore"

jobs:
  release:
    uses: canonical/observability/.github/workflows/charm-release.yaml@f09a6a6b1982e7c8d8fb84b1cfd73070b44a1ca2 # v1
    secrets: inherit
    with:
      provider: machine
