name: Tiobe TiCS Analysis

on:
    workflow_dispatch:
    schedule:
    - cron: "0 0 * * 1"  # Runs at midnight UTC every Monday

jobs:
    tics:
        name: TiCs
        uses: canonical/observability/.github/workflows/charm-tiobe-scan.yaml@f09a6a6b1982e7c8d8fb84b1cfd73070b44a1ca2 # v1
        secrets: inherit
